--- # This playbook will install docker on Centos 7
- hosts: all
  become: yes

  tasks:
  - name: remove old docker
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

  - name: install yum-utils
    yum:
      name: yum-utils
      state: latest

  - name: Add docker repository
    shell:
      cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker-ce
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    notify: docker install

  handlers:
  - name: Start docker service
    service:
      name: docker
      state: restarted
    listen: docker install
