--- # This playbook will install docker on Centos 7
- hosts: all
  become: yes
  vars:
    URL: 192.168.56.10
  tasks:
  - name: Install python2-pip
    yum:
      name: python2-pip
      state: latest
      
  - name: Installing docker python library using Ansible pip module
    pip:
      name: docker

  - name: Add docker repository
    copy:
      src: /vagrant/files/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: Install docker-ce
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Start docker service
    service:
      name: docker
      state: started

  - name: create mysql folder
    file:
      path: /apps/mysql
      state: directory

  - name: create wordpress folder
    file:
      path: /apps/wordpress
      state: directory

  - name: create nginx folder
    file:
      path: /apps/nginx
      state: directory

  - name: copy nginx config
    copy:
      src: /vagrant/files/proxy.conf
      dest: /apps/nginx/default.conf

  - name: Create a network
    docker_network:
      name: wpnet

  - name: start mysql container
    docker_container:
      name: mysql
      image: mysql:5.7
      state: started
      restart: yes
      restart_policy: unless-stopped
      env:
        MYSQL_DATABASE: wordpressdb
        MYSQL_USER: wordpressuser
        MYSQL_PASSWORD: wordpresspass
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
      volumes:
         - /apps/mysql:/var/lib/mysql
      networks:
        - name: wpnet
          aliases: mysql
        
  - name: start wordpress container
    docker_container:
      name: wordpress
      image: wordpress
      state: started
      restart: yes
      restart_policy: unless-stopped
      env:
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_USER: wordpressuser
        WORDPRESS_DB_PASSWORD: wordpresspass
        WORDPRESS_DB_NAME: wordpressdb
      volumes:
        - /apps/wordpress:/var/www/html
      networks:
        - name: wpnet
          aliases: wordpress

  - name: Update Wordpress config file
    lineinfile:
      path: /apps/wordpress/wp-config.php
      line: define('WP_HOME','http://{{ URL }}');

  - name: Update Wordpress config file
    lineinfile:
      path: /apps/wordpress/wp-config.php
      line: define('WP_SITEURL','http://{{ URL }}');
 
  - name: start nginx container
    docker_container:
      name: nginx
      image: nginx
      state: started
      restart: yes
      restart_policy: unless-stopped
      ports:
        - "80:80"
      volumes:
        - /apps/nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - name: wpnet
          aliases: nginx